### ISSUE TITLE
First PR title

### ISSUE THREAD

**Issue by hectorsector** [githubtraining/react-course#16]
The title of the first pull request can probably be something more meaningful that defines what the learner is doing in the pull request.

**Comment by brianamarie** [comment]
Additionally, this is leading to a bug. I experienced an error when I used a different PR title, and unfortunately the "unhappy path" of the gate wasn't prepared for it. 

I intend to open a PR to remove this gate.

Error in introduction-to-react:open-a-pull-request:gate[0].else:respond[0]

```
Error: Response [Make sure the title of your PR is "Changes"] does not exist.
    at Context.fromFile (/usr/src/learning-lab/lib/context.js:121:13)
    at async module.exports (/usr/src/learning-lab/node_modules/@github/learning-lab-components/actions/respond/index.js:22:11)
    at async Context.runActions (/usr/src/learning-lab/lib/context.js:228:24)
    at async module.exports (/usr/src/learning-lab/node_modules/@github/learning-lab-components/actions/gate/index.js:33:5)
    at async Context.runActions (/usr/src/learning-lab/lib/context.js:228:24)
    at async Course.runHandler (/usr/src/learning-lab/lib/course.js:174:32)
```
